START TRANSACTION;

UPDATE provi SET name = 'Agrigento' WHERE cod_provi = 'AG';
UPDATE provi SET name = 'Alessandria' WHERE cod_provi = 'AL';
UPDATE provi SET name = 'Ancona' WHERE cod_provi = 'AN';
UPDATE provi SET name = 'Aosta' WHERE cod_provi = 'AO';
UPDATE provi SET name = 'Arezzo' WHERE cod_provi = 'AR';
UPDATE provi SET name = 'Ascoli Piceno' WHERE cod_provi = 'AP';
UPDATE provi SET name = 'Asti' WHERE cod_provi = 'AT';
UPDATE provi SET name = 'Avellino' WHERE cod_provi = 'AV';
UPDATE provi SET name = 'Bari' WHERE cod_provi = 'BA';
UPDATE provi SET name = 'Barletta Andria Trani' WHERE cod_provi = 'BT';
UPDATE provi SET name = 'Belluno' WHERE cod_provi = 'BL';
UPDATE provi SET name = 'Benevento' WHERE cod_provi = 'BN';
UPDATE provi SET name = 'Bergamo' WHERE cod_provi = 'BG';
UPDATE provi SET name = 'Biella' WHERE cod_provi = 'BI';
UPDATE provi SET name = 'Bologna' WHERE cod_provi = 'BO';
UPDATE provi SET name = 'Bolzano' WHERE cod_provi = 'BZ';
UPDATE provi SET name = 'Brescia' WHERE cod_provi = 'BS';
UPDATE provi SET name = 'Brindisi' WHERE cod_provi = 'BR';
UPDATE provi SET name = 'Cagliari' WHERE cod_provi = 'CA';
UPDATE provi SET name = 'Caltanissetta' WHERE cod_provi = 'CL';
UPDATE provi SET name = 'Campobasso' WHERE cod_provi = 'CB';
UPDATE provi SET name = 'Carbonia Iglesias' WHERE cod_provi = 'CI';
UPDATE provi SET name = 'Caserta' WHERE cod_provi = 'CE';
UPDATE provi SET name = 'Catania' WHERE cod_provi = 'CT';
UPDATE provi SET name = 'Catanzaro' WHERE cod_provi = 'CZ';
UPDATE provi SET name = 'Chieti' WHERE cod_provi = 'CH';
UPDATE provi SET name = 'Como' WHERE cod_provi = 'CO';
UPDATE provi SET name = 'Cosenza' WHERE cod_provi = 'CS';
UPDATE provi SET name = 'Cremona' WHERE cod_provi = 'CR';
UPDATE provi SET name = 'Crotone' WHERE cod_provi = 'KR';
UPDATE provi SET name = 'Cuneo' WHERE cod_provi = 'CN';
UPDATE provi SET name = 'Enna' WHERE cod_provi = 'EN';
UPDATE provi SET name = 'Fermo' WHERE cod_provi = 'FM';
UPDATE provi SET name = 'Ferrara' WHERE cod_provi = 'FE';
UPDATE provi SET name = 'Firenze' WHERE cod_provi = 'FI';
UPDATE provi SET name = 'Foggia' WHERE cod_provi = 'FG';
UPDATE provi SET name = 'Forlì Cesena' WHERE cod_provi = 'FC';
UPDATE provi SET name = 'Frosinone' WHERE cod_provi = 'FR';
UPDATE provi SET name = 'Genova' WHERE cod_provi = 'GE';
UPDATE provi SET name = 'Gorizia' WHERE cod_provi = 'GO';
UPDATE provi SET name = 'Grosseto' WHERE cod_provi = 'GR';
UPDATE provi SET name = 'Imperia' WHERE cod_provi = 'IM';
UPDATE provi SET name = 'Isernia' WHERE cod_provi = 'IS';
UPDATE provi SET name = 'La Spezia' WHERE cod_provi = 'SP';
UPDATE provi SET name = 'L''Aquila' WHERE cod_provi = 'AQ';
UPDATE provi SET name = 'Latina' WHERE cod_provi = 'LT';
UPDATE provi SET name = 'Lecce' WHERE cod_provi = 'LE';
UPDATE provi SET name = 'Lecco' WHERE cod_provi = 'LC';
UPDATE provi SET name = 'Livorno' WHERE cod_provi = 'LI';
UPDATE provi SET name = 'Lodi' WHERE cod_provi = 'LO';
UPDATE provi SET name = 'Lucca' WHERE cod_provi = 'LU';
UPDATE provi SET name = 'Macerata' WHERE cod_provi = 'MC';
UPDATE provi SET name = 'Mantova' WHERE cod_provi = 'MN';
UPDATE provi SET name = 'Massa Carrara' WHERE cod_provi = 'MS';
UPDATE provi SET name = 'Matera' WHERE cod_provi = 'MT';
UPDATE provi SET name = 'Messina' WHERE cod_provi = 'ME';
UPDATE provi SET name = 'Milano' WHERE cod_provi = 'MI';
UPDATE provi SET name = 'Modena' WHERE cod_provi = 'MO';
UPDATE provi SET name = 'Monza e della Brianza' WHERE cod_provi = 'MB';
UPDATE provi SET name = 'Napoli' WHERE cod_provi = 'NA';
UPDATE provi SET name = 'Novara' WHERE cod_provi = 'NO';
UPDATE provi SET name = 'Nuoro' WHERE cod_provi = 'NU';
UPDATE provi SET name = 'Olbia Tempio' WHERE cod_provi = 'OT';
UPDATE provi SET name = 'Oristano' WHERE cod_provi = 'OR';
UPDATE provi SET name = 'Padova' WHERE cod_provi = 'PD';
UPDATE provi SET name = 'Palermo' WHERE cod_provi = 'PA';
UPDATE provi SET name = 'Parma' WHERE cod_provi = 'PR';
UPDATE provi SET name = 'Pavia' WHERE cod_provi = 'PV';
UPDATE provi SET name = 'Perugia' WHERE cod_provi = 'PG';
UPDATE provi SET name = 'Pesaro e Urbino' WHERE cod_provi = 'PU';
UPDATE provi SET name = 'Pescara' WHERE cod_provi = 'PE';
UPDATE provi SET name = 'Piacenza' WHERE cod_provi = 'PC';
UPDATE provi SET name = 'Pisa' WHERE cod_provi = 'PI';
UPDATE provi SET name = 'Pistoia' WHERE cod_provi = 'PT';
UPDATE provi SET name = 'Pordenone' WHERE cod_provi = 'PN';
UPDATE provi SET name = 'Potenza' WHERE cod_provi = 'PZ';
UPDATE provi SET name = 'Prato' WHERE cod_provi = 'PO';
UPDATE provi SET name = 'Ragusa' WHERE cod_provi = 'RG';
UPDATE provi SET name = 'Ravenna' WHERE cod_provi = 'RA';
UPDATE provi SET name = 'Reggio Calabria' WHERE cod_provi = 'RC';
UPDATE provi SET name = 'Reggio Emilia' WHERE cod_provi = 'RE';
UPDATE provi SET name = 'Rieti' WHERE cod_provi = 'RI';
UPDATE provi SET name = 'Rimini' WHERE cod_provi = 'RN';
UPDATE provi SET name = 'Roma' WHERE cod_provi = 'RM';
UPDATE provi SET name = 'Rovigo' WHERE cod_provi = 'RO';
UPDATE provi SET name = 'Salerno' WHERE cod_provi = 'SA';
UPDATE provi SET name = 'Medio Campidano' WHERE cod_provi = 'VS';
UPDATE provi SET name = 'Sassari' WHERE cod_provi = 'SS';
UPDATE provi SET name = 'Savona' WHERE cod_provi = 'SV';
UPDATE provi SET name = 'Siena' WHERE cod_provi = 'SI';
UPDATE provi SET name = 'Siracusa' WHERE cod_provi = 'SR';
UPDATE provi SET name = 'Sondrio' WHERE cod_provi = 'SO';
UPDATE provi SET name = 'Taranto' WHERE cod_provi = 'TA';
UPDATE provi SET name = 'Teramo' WHERE cod_provi = 'TE';
UPDATE provi SET name = 'Terni' WHERE cod_provi = 'TR';
UPDATE provi SET name = 'Torino' WHERE cod_provi = 'TO';
UPDATE provi SET name = 'Ogliastra' WHERE cod_provi = 'OG';
UPDATE provi SET name = 'Trapani' WHERE cod_provi = 'TP';
UPDATE provi SET name = 'Trento' WHERE cod_provi = 'TN';
UPDATE provi SET name = 'Treviso' WHERE cod_provi = 'TV';
UPDATE provi SET name = 'Trieste' WHERE cod_provi = 'TS';
UPDATE provi SET name = 'Udine' WHERE cod_provi = 'UD';
UPDATE provi SET name = 'Varese' WHERE cod_provi = 'VA';
UPDATE provi SET name = 'Venezia' WHERE cod_provi = 'VE';
UPDATE provi SET name = 'Verbano Cusio Ossola' WHERE cod_provi = 'VB';
UPDATE provi SET name = 'Vercelli' WHERE cod_provi = 'VC';
UPDATE provi SET name = 'Verona' WHERE cod_provi = 'VR';
UPDATE provi SET name = 'Vibo Valentia' WHERE cod_provi = 'VV';
UPDATE provi SET name = 'Vicenza' WHERE cod_provi = 'VI';
UPDATE provi SET name = 'Viterbo' WHERE cod_provi = 'VT';

COMMIT;